### ISSUE TITLE
Error running on Ubuntu 20.04: undefined symbol: FT_Done_MM_Var

### ISSUE THREAD

**Issue by XlashDev** [novelda/XeThru-Explorer#1]
Hi, I have a X4M200 incoming and looking how to interface it in Raspberry Pi. Saw a post using this software to check if it is on latest firmware. I'm using Ubuntu 20.04. Upon running app image it shows this error. 

`./XethruExplorer.AppImage: symbol lookup error: /lib/x86_64-linux-gnu/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var`

**Comment by XlashDev** [comment]
solve with 

`LD_PRELOAD=/lib/x86_64-linux-gnu/libfreetype.so ./XethruExplorer.AppImage `

**Comment by sushakam** [comment]
Wow that worked. Thank you dearly.
